### PR TITLE
Add usePolling option

### PR DESCRIPTION
**Pull request by stilllife00**
I would like to pass to chokidar the usePolling option.
This is needed for certain VMs like Vagrant which doesn't properly support watch

### CODE REVIEW

**Comment by stilllife00** [comment]
@michaelwayman Some checks are failing but AFAIK they are not related with the code of this PR. Can you please take a look ?

**Comment by michaelwayman** [comment]
Soo sorry @stilllife00 for taking so long getting back to you. Between work and life I completely missed this. Yeah let's get the polling option going

**Comment by michaelwayman** [comment]
I resolved the merge conflicts so this should be able to merge, I just need to test it real quick and we can publish it, thanks for your contribution :)

**Comment by michaelwayman** [comment]
`--use-polling` is now in `node-sass-chokidar@1.2.0`

**Comment by stilllife00** [comment]
thanks!

**Pull request merged**
