### PR TITLE
Upgrade `node-sass` to v4.5.3 which has Node 8 support

### PR DESCRIPTION
**Pull request by anmonteiro**
related issue: https://github.com/sass/node-sass/pull/1969

### CODE REVIEW

**Comment by michaelwayman** [comment]
closes #9

**Comment by michaelwayman** [comment]
We should probably add `node 8` to the travis build here
https://github.com/michaelwayman/node-sass-chokidar/blob/master/.travis.yml#L2

I can do it in a separate PR if you want me to merge this first, just let me know

**Comment by anmonteiro** [comment]
@michaelwayman I pushed a new commit adding Node 8 to the build matrix Let me know if you want me to squash my commits.

**Comment by michaelwayman** [comment]
no need to squash, the 2 commits are logically different/separate.
Tests passed on `node 8` 💯  once they finish I will merge.

Again, thanks for the help.

**Comment by michaelwayman** [comment]
Finally got this on npm with `node-sass-chokidar v0.0.3`. Thanks again for the help.

**Pull request merged**
