### PR TITLE
Logic to build before watch

### PR DESCRIPTION
**Pull request by nickswiss**
Adds logic for new flag:

```-b, --build-first          Transpiles all SCSS before watching```

Providing this flag alongside `--watch` will result in the provided directory/file being transpiled before watching this path, alleviating the need for chaining these calls.

Example:
`node-sass-chokidar src/ -o src/ && node-sass-chokidar src/ -o src/ --watch --recursive` 
becomes
`node-sass-chokidar src/ -o src/ --watch --recursive -b`

### CODE REVIEW

**Comment by michaelwayman** [comment]
This looks good to me.
Is there anything we need to test?

**Comment by michaelwayman** [comment]
Also, the flag name, I am not sure how I feel about `--build-first`..
Maybe something like `--force-build` and it will always build?

IDK what are your thoughts? Once we name it, we can't go back and change it so I want to really encapsulate the essence.

Once we settle on a name let's make the short description fleek too.

**Comment by filoxo** [comment]
Is there any reason this hasn't been merged yet? Seems like it'd be the best default behavior.

**Comment by eMerzh** [comment]
@filoxo conflicts at least now... :) 
@michaelwayman about the naming i like the `--skip-initial` proposed by @nickswiss

**Comment by michaelwayman** [comment]
@filoxo merging this
@eMerzh adds the `--skip-initial` flag as well
@nickswiss finally getting around to merging this, thanks for the help 👍 

This will be published as  v1.1.0 some time today.

Do let me know if there are issues.

**Pull request merged**
